### ISSUE TITLE
unity3d script marathi font rendering issue

### ISSUE THREAD

**Issue by lightstriker12** [abusaadp/Unity3dHindiRenderer#1]
hello, can someone please help me? In unity 3d the default fonts for devnagri have broken glyphs so want to write a new script to make the glyphs appear correctly as they appear in a notepad doc. please help.

**Comment by abusaadp** [comment]
Can you please send me the text which is not rendering properly in Unity3d for Marathi

**Comment by lightstriker12** [comment]
hi, I want to create a similar program for devnagri. I am new at programming and would like to know how to create a program for it.

**Comment by abusaadp** [comment]
Please clone my repository and open it in Unity3d, you can use the script in this project for rendering in devanagari font. Try the sample code and inform what is not working for you.

**Comment by lightstriker12** [comment]
thanks I will check the code once again, I really need to understand the code first if you have any flowchart that would really help me.

**Comment by abusaadp** [comment]
I will update the readme to explain this project.

**Comment by lightstriker12** [comment]
if possible could you comment in source code as well? thanks a lot for the readme update if possible please comment in the program for the steps taken. Thank you

**Comment by abusaadp** [comment]
Did it work for you? Are you still having any difficulty in getting this to work?

**Comment by sirlemonho** [comment]
How do i get Devanagari Font to work? (:

**Comment by SurajSangve** [comment]
Hii @abusaadp can you render मुख्य मेनू में वापस जाएं , कुल कंप्रेशन in unity3d using text and TMP

**Comment by SurajSangve** [comment]
> Did it work for you? Are you still having any difficulty in getting this to work?

कुल कंप्रेशन,  मुख्य मेनू में वापस जाएं

**Comment by abusaadp** [comment]
It works for me. What did you try and why is it not working for you? What is the issue you are facing?
