### ISSUE TITLE
English text in Krutidev

### ISSUE THREAD

**Issue by RahulKumar094** [abusaadp/Unity3dHindiRenderer#2]
I wanted to give users my website so that they contact me if required.
Using Krutidev font doesn't allow me have english content in the string.
How can ignore some english words to be translated into Hindi ?
I have no knowledge of Typoghaphic coding so dont even whether I can do it or not.
Please Help...

**Comment by RahulKumar094** [comment]
![screenshot 10](https://user-images.githubusercontent.com/29048296/42810489-af32ba74-89d5-11e8-8c02-c6554d194d31.png)
![screenshot 11](https://user-images.githubusercontent.com/29048296/42810490-af612170-89d5-11e8-83e5-dc3efd16e5f8.png)

**Comment by abusaadp** [comment]
It is very simple. You can have two Text elements side by side. In the first Text element use English font with your website address in English. In the second text element use krutidev font with Hindi text. Remember to have some spacing between the two Text elements.
