### ISSUE TITLE
Does not work in Unity 2018.3

### ISSUE THREAD

**Issue by sathyarajshetigar** [abusaadp/Unity3dHindiRenderer#3]
When I try to play the game in the editor. Editor freezes and crashes.

**Comment by gbogarinb** [comment]
I'm having the same problem with 2018.2.

**Comment by kirivasile** [comment]
I had similar problem with 2019.4.
It was infinite loop. I fixed this with replacing `while` with `for`. I didn't find differences in language.
Or you can try search problem loop.

**Comment by akshaybharwani** [comment]
@kirivasile could you share your code? Would be a huge help.

**Comment by kirivasile** [comment]
@akshaybharwani Sorry, I don't think I can share the code itself. 
But the idea is to change `UnicodeToKrutidev.cs`
Replace all `while condition` loops with `for` + `if condition`. For example, with 10000 iterations.

**Comment by akshaybharwani** [comment]
Ah thanks! Will try it out.
